authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import geekshop.views as geekshop
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', geekshop.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', geekshop.contact, name='contact'),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', cache_page(3600)(mainapp.products), name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='обновлено')

    def __str__(self):
        return f'{self.pk} -- {self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    image = models.ImageField(upload_to='product_images', blank=True, verbose_name='картинка продукта')
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name='создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='обновлено')

    def __str__(self):
        return f'{self.name} -- {self.category.name}'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

mainapp/views.py
import random

from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page

from basketapp.models import Basket
from mainapp.models import ProductCategory, Product

main_menu = [
        {'href': 'main', 'name': 'домой'},
        {'href': 'contact', 'name': 'контакты'},
        {'href': 'products:index', 'name': 'продукты'},
]


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

    return same_products


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


@cache_page(3600)
def products(request, pk=None, page=1):

    title = 'каталог/продукты'
    links_menu = get_links_menu()
    basket = get_basket(request.user)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category').\
                order_by('price')
        else:
            category = get_category(pk)
            products = Product.objects.filter(category__pk=pk, is_active=True,
                                              category__is_active=True).select_related('category').order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'main_menu': main_menu,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'title': title,
        }
        return render(request, 'mainapp/products_list.html', context=context)

    context = {
        'main_menu': main_menu,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'title': title,
    }
    return render(request, 'mainapp/products.html', context=context)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'main_menu': main_menu,
        'links_menu': get_links_menu(),
        'product': get_object_or_404(Product, pk=pk),
    }

    return render(request, 'mainapp/product.html', content)

mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'geekshop/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}"
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products.html
		{% extends 'geekshop/base.html' %}
		{% load static %}

		{% block slider %}
		<div class="hero-white">
			{% include 'geekshop/includes/inc_menu.html' %}
		</div>
		{% endblock slider %}

		{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'geekshop/includes/inc_categories_menu.html' %}
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/media/{{ hot_product.image }}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> {{ hot_product.price }} <span>руб</span></p>
					<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{ hot_product.description }}
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for product in same_products %}
					<div class="block">
						<a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="">
							<div class="text">
								<img src="{% static '/img/icon-hover.png' %}" alt="img">
								<h4>{{ product.description }}</h4>
								<p>{{ product.description }}</p>
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
		{% endblock content %}

mainapp/templates/mainapp/products_list.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'geekshop/includes/inc_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'geekshop/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
        <div class="title clearfix">
            <h2>Категория: "{{ category.name|title }}"</h2>
            <div class="paginator">
                {% if products.has_previous %}
                <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                    <
                </a>
                {% endif %}
                <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
                {% if products.has_next %}
                <a href="{% url 'products:page' category.pk products.next_page_number %}">
                    >
                </a>
                {% endif %}
            </div>
        </div>
        <div class="category-products clearfix">
            <div class="tab-content">
                {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:product' product.pk %}">
                        <img src="/media/{{ product.image }}" alt="product">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.description }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
                <div class="tab-content">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}