authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import geekshop.views as geekshop
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', geekshop.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', geekshop.contact, name='contact'),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', cache_page(3600)(mainapp.products), name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
   path('', ordersapp.OrderList.as_view(), name='orders_list'),
   path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
   path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
   path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
   path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
   path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
   path('product/<int:pk>/price/', ordersapp.get_product_price),
]

geekshop/views.py
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product


main_menu = [
        {'href': 'main', 'name': 'домой'},
        {'href': 'contact', 'name': 'контакты'},
        {'href': 'products:index', 'name': 'продукты'},
]
main_products = [
    {'src': '/img/product-1.jpg', 'h4': 'Отличный стул', 'p': 'Расположитесь комфортно.'},
    {'src': '/img/product-2.jpg', 'h4': 'Стул повышенного качества', 'p': 'Не оторваться.'},
    {'src': '/img/product-3.jpg', 'h4': 'Отличный стул', 'p': 'Расположитесь комфортно.'},
    {'src': '/img/product-4.jpg', 'h4': 'Стул повышенного качества', 'p': 'Не оторваться.'},
]


def main(request):
    title = 'главная'
    main_products_base = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')[:4]
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user).select_related('user')

    context = {
        'main_menu': main_menu,
        'main_products': main_products_base,
        'title': title,
        'basket': basket,
    }
    return render(request, 'geekshop/index.html', context=context)


def contact(request):
    title = 'контакты'
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user).select_related('user')
    context = {
        'main_menu': main_menu,
        'title': title,
        'basket': basket,
    }
    return render(request, 'geekshop/contact.html', context=context)

geekshop/templates/geekshop/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}"
           class="{% if request.resolver_match.kwargs.pk == 0 %}
                active
              {% endif %}">
            все
        </a>
    </li>
    {% for link in links_menu %}
    <li>
        <a href="{% url 'products:category' link.pk %}"
           class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                  active
                {% endif %}">
            {{ link.name }}
        </a>
    </li>
    {% endfor %}
</ul>

geekshop/templates/geekshop/includes/inc_menu.html
<div class="header clearfix">
    <a href="{% url 'main' %}" class="logo"></a>
    <ul class="menu">
        {% for link in main_menu %}
        <li><a href="{% url link.href %}" class="{% if request.resolver_match.view_name == link.href %} active
		{% endif %}">{{ link.name }}</a></li>
        {% endfor %}
        {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown" role="button" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <div class="dropdown-menu">

                        <a href="{% url 'auth:edit' %}" class="dropdown-item">
                            профиль
                        </a>


                        <a href="{% url 'ordersapp:orders_list' %}" class="dropdown-item">
                            заказы
                        </a>

                </div>
            </div>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:view' %}" class="basket">
    <span>
    {% if basket %}
      {{ basket.0.total_cost|floatformat:0 }} руб
      ({{ basket.0.total_quantity }} шт)
    {% endif %}
  </span>

    </a>
</div>